### ISSUE TITLE
Improve the footer of the landing page of the new Smoothie App

### ISSUE THREAD

**Issue by Aarthy153** [openfoodfacts/smoothielanding#27]
###PROBLEM 
The footer is not attractive and doesn't seem to have a good structure. 

![image](https://user-images.githubusercontent.com/69035013/209765927-4ccc344d-1bfc-4d10-9651-0a88cae8c8e1.png)

###PROPOSED SOLUTION
The proposed solution is to organize the content of the footer and give a proper structure to match the whole body and header. 
A properly structured footer like this will be implemented.

![image](https://user-images.githubusercontent.com/69035013/209765839-cfe7318e-bb41-406e-9846-2da3fa7aafb3.png)

###Are you working on this issue?
Yes

**Comment by Sudhanva-Nadiger** [comment]
@Aarthy153 are you still working on this ?
