### ISSUE TITLE
Add QR codes to access the smooth app by scanning it from mobile. 

### ISSUE THREAD

**Issue by Aarthy153** [openfoodfacts/smoothielanding#29]
### Problem
Most users may not be logged in to the play store/ app store on their PC/Laptop.

### Proposed solution
A QR-Code can be placed in order to provide the users to scan them and navigate to the play store/App store. 

### Are you working on this issue?
Yes

**Comment by Aarthy153** [comment]
@teolemon Requesting review for the PR and the other new issues I have created.

**Comment by M123-dev** [comment]
Great idea
