### ISSUE TITLE
Add automatic deployment for the Smoothie landing page on the Open Food Facts servers

### ISSUE THREAD

**Issue by teolemon** [openfoodfacts/smoothielanding#3]
### What
- [ ] The landing page designed by Cal is already cool
- [ ] It is deployed at https://openfoodfacts.github.io/smoothielanding/
- [ ] Can we deploy it automatically on the server, a bit like openfoodfacts-web ?
### Part of 
- Launch Smoothie

**Comment by alexgarel** [comment]
@teolemon does it still have sense with the site redesign ?
